### ISSUE TITLE
Error: Parameter 'toolPath' cannot be null or empty.

### ISSUE THREAD

**Issue by bahadir-be** [Winvision/vsts-tasks#34] opened 2022-10-27 14:06 UTC
![image](https://user-images.githubusercontent.com/62173919/198307261-ec3e0491-4336-41a3-a080-439c91c77ec6.png)

I faced the above problem, any idea?

**Comment by rahim3216** [comment] 2022-10-28 21:19
Facing the same issue.
![image](https://user-images.githubusercontent.com/32245726/198734646-dc937eb0-53f5-4347-b9fd-5db1a72c1e96.png)

**Comment by wynandjordaan** [comment] 2022-11-01 11:10
Duplicate of https://github.com/Winvision/vsts-tasks/issues/33

**Comment by Arodriguez81** [comment] 2022-11-03 16:12
In the meantime what we can do is to do it from cli until they fix it.

***Create a powershell task to download dt.
Invoke-WebRequest -Uri "https://github.com/Azure/azure-documentdb-datamigrationtool/releases/download/1.8.3/azure-documentdb-datamigrationtool-1.8.3.zip" -OutFile "$(System.DefaultWorkingDirectory)\dt-1.8.3.zip"
***Unzip it
steps:

    task: ExtractFiles@1
    displayName: 'Extract files '
    inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/dt-1.8.3.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/dt-1.8.3'
    ***Command line
    cd $(System.DefaultWorkingDirectory)/dt-1.8.3/azure-documentdb-datamigrationtool-1.8.3
    dt (copy the command from desktop version view command once you have the connections setup and pasted here.)
    *** Run pipeline

**Comment by Nimtz89** [comment] 2023-04-25 07:34
Duplicate of #33 , PR opened to fix issue

**Closed as completed by Nimtz89** 2023-04-25 07:34 UTC
